spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: root
  redis:
    host: localhost
    port: 6379

logging:
  level:
    web: debug
    org:
      ling: debug

debug: true
